### ISSUE TITLE
Include iTunes ID with database export

### ISSUE THREAD

**Issue by mitchdowney** [Podcastindex-org/database#1]
Would it be possible to share the iTunes ID with the database export? If people are concerned about cloned feeds / malicious content, then they could use the iTunes ID to verify a feed is already hosted by Apple, and if it is hosted by Apple, then there is some reassurance that the feed is safe. If the iTunes ID is available in a separate CSV that can be cross-referenced with the newsfeeds CSV that would be fine.

I know longer-term the goal is to break away from Apple dependency completely, but I think in the short-term the Apple ID would be useful for developers switching from Apple to Podcast Index.

**Comment by daveajones** [comment]
Yes it will be in there if we have it. That column should be in the sample export.

**Comment by mitchdowney** [comment]
Oh my bad, I was thinking the readme contained a full list of fields, but I see the itunes_id in the CSV now. Thanks!
