### ISSUE TITLE
Data issue: I Hear Things

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#13]
https://podcastindex.org/search?q=i%20hear%20things

https://podcastindex.org/podcast/3327613
https://feeds.transistor.fm/i-hear-things

https://podcastindex.org/podcast/3944053
https://api.substack.com/feed/podcast/5694.rss

3944053 points to a deleted substack, none of the enclosures are available, should probably delete it

**Comment by daveajones** [comment]
fixed
