### ISSUE TITLE
Data issue: JavaScript Jabber

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#15]
https://podcastindex.org/search?q=javascript%20jabber

https://podcastindex.org/podcast/836965
https://javascriptjabber.com/rss

https://podcastindex.org/podcast/1059862
https://feeds.fireside.fm/javascriptjabber/rss

https://javascriptjabber.com/rss 302s (temporary redirect) over to https://feeds.fireside.fm/javascriptjabber/rss

**Comment by daveajones** [comment]
fixed
