### ISSUE TITLE
Data issue: HTTP 203

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#16]
https://podcastindex.org/search?q=http%20203

https://podcastindex.org/podcast/879614
http://feeds.feedburner.com/Http203Podcast

https://podcastindex.org/podcast/4577989
https://developers.google.com/web/shows/http203/podcast/feed.xml

http://feeds.feedburner.com/Http203Podcast has newer content

**Comment by daveajones** [comment]
fixed
