### ISSUE TITLE
Data issue: EconTalk

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#17]
https://podcastindex.org/search?q=econtalk

https://podcastindex.org/podcast/204499
https://feeds.simplecast.com/wgl4xEgL

https://podcastindex.org/podcast/2450883
https://feeds.feedburner.com/Econtalk

https://feeds.feedburner.com/Econtalk appears to be abandoned, should probably delete it

**Comment by daveajones** [comment]
fixed
