### ISSUE TITLE
Data issue: The BS Filter

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#18]
https://podcastindex.org/search?q=bs%20filter

https://podcastindex.org/podcast/1116509
https://thebullshitfilter.com/feed/podcast

https://podcastindex.org/podcast/2501706
https://thebullshitfilter.com/feed/

Same content, site uses WP and Blubrry PowerPress

https://podcasts.apple.com/us/podcast/the-bs-filter/id1210589252
points to
https://thebullshitfilter.com/feed/podcast

**Comment by daveajones** [comment]
fixed.
