### ISSUE TITLE
Data issue: Foodball

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#20]
https://anchor.fm/s/2265c300/podcast/rss
AP: https://podcasts.apple.com/us/podcast/foodball/id1616894386

This cannot be added to PI ("already exists") but does not appear in search, even by feed url.

Incorrectly marked as dead?

This is definitely a live and current show that should exist in the index.

**Comment by daveajones** [comment]
Hmm.  Seems fine to me.  Maybe it 404'd for a bit or something.  Not sure:

https://podcastindex.org/search?q=foodball

**Comment by johnspurlock** [comment]
Yea this one I went to the boards for: https://podcastindex.social/web/@js/108204513777071918

**Comment by daveajones** [comment]
Oh yeah. Duh. I knew that sounded familiar. 😂
