### ISSUE TITLE
Data issue: Real Time with Bill Maher

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#21]
https://podcastindex.org/search?q=real%20maher

https://podcastindex.org/podcast/742515
https://www.omnycontent.com/d/playlist/d83f52e4-2455-47f4-982e-ab790120b954/40b4061b-113f-41d1-8e49-ad08002e1360/1145399f-284b-4295-9fbb-ad08002e1372/podcast.rss
current

https://podcastindex.org/podcast/3959422
https://anchor.fm/s/359dd674/podcast/rss
out of date

https://podcastindex.org/podcast/1237273
https://audioboom.com/channels/2382598.rss
way out of date

**Comment by daveajones** [comment]
fixed
