### ISSUE TITLE
Data issue: Song Exploder

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#22]
https://podcastindex.org/search?q=song%20exploder

Official feed:

https://podcastindex.org/podcast/390830
http://feed.songexploder.net/SongExploder

Test or spam feeds:

https://podcastindex.org/podcast/5329628
https://feeds.buzzsprout.com/1972754.rss

https://podcastindex.org/podcast/5329638
https://feeds.buzzsprout.com/1972696.rss

https://podcastindex.org/podcast/5329641
https://feeds.buzzsprout.com/1972759.rss

https://podcastindex.org/podcast/5329651
https://feeds.buzzsprout.com/1972765.rss

https://podcastindex.org/podcast/5329670
https://feeds.buzzsprout.com/1972179.rss

https://podcastindex.org/podcast/3826347
https://media.rss.com/davisbandsdavis/feed.xml

https://podcastindex.org/podcast/5329623
https://feeds.buzzsprout.com/1972760.rss

https://podcastindex.org/podcast/5329668
https://feeds.buzzsprout.com/1972757.rss

https://podcastindex.org/podcast/4456833
https://feeds.buzzsprout.com/895945.rss

**Comment by johnspurlock** [comment]
RSS.com deleted https://media.rss.com/davisbandsdavis/feed.xml
it now 404s

**Comment by johnspurlock** [comment]
Buzzsprout deleted theirs, all of them 404 now as well

**Comment by daveajones** [comment]
fixed.
