### ISSUE TITLE
Data issue: St. Louis on the Air

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#23]
https://podcastindex.org/search?q=louis%20on%20the%20air

Official: 
https://podcastindex.org/podcast/41584
https://kwmu-rss.streamguys1.com/stl_on_the_air/st-louis-on-the-air-itunes.xml

Out of date, spreaker clone?
https://podcastindex.org/podcast/4647087
https://www.spreaker.com/show/5013049/episodes/feed

**Comment by daveajones** [comment]
fixed.
