### ISSUE TITLE
Data issue: On Point WBUR

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#25]
https://podcastindex.org/search?q=on%20point%20wbur

https://podcastindex.org/podcast/907915
https://rss.wbur.org/onpoint/podcast
current
AP points to this

https://podcastindex.org/podcast/2434620
https://rss.wbur.org/onpoint/rss
same content, but no author or category

https://podcastindex.org/podcast/3696832
https://rss.wbur.org/onpoint/week-in-the-news/podcast
not updated since jan 2021

https://podcastindex.org/podcast/2501374
https://anchor.fm/s/1a4f4a60/podcast/rss
not updated since march 2020

**Comment by daveajones** [comment]
fixed.
