### ISSUE TITLE
Data issue: Making Sense with Sam Harris

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#26]
https://podcastindex.org/search?q=making%20sense%20harris

https://podcastindex.org/podcast/423291
https://wakingup.libsyn.com/rss
official public feed

https://podcastindex.org/podcast/4846034
https://rss.samharris.org/feed?id=exisng
expired private feed

https://podcastindex.org/podcast/4435552
https://rss.making-sense.samharris.org/feed/?token=febac488-47d0-4e6b-bba8-0e28956e55d6
subscriber only content, private feed with token

https://podcastindex.org/podcast/5337904
https://api.substack.com/feed/podcast/471899.rss
subscriber only content, can't find the associated substack site, maybe a clone?  

https://podcastindex.org/podcast/3778856
https://www.breaker.audio/feeds/2599261.rss
old breaker link, everything offline, should be deleted

**Comment by daveajones** [comment]
fixed.
