### ISSUE TITLE
Data issue: On The Media

### ISSUE THREAD

**Issue by johnspurlock** [Podcastindex-org/database#27]
https://podcastindex.org/search?q=on%20the%20media

https://podcastindex.org/podcast/556636
http://feeds.wnyc.org/onthemedia
current
AP points to this

https://podcastindex.org/podcast/1566812
https://www.wnycstudios.org/feeds/shows/otm
current
not a podcast feed, contains many articles as well

https://podcastindex.org/podcast/2258919
https://anchor.fm/s/13dde95c/podcast/rss
feb 2020, anchor clone

**Comment by daveajones** [comment]
Fixed.
