### ISSUE TITLE
What is the scale for popularityScore?

### ISSUE THREAD

**Issue by ryan-lp** [Podcastindex-org/database#38]
According to [TRITON DIGITAL](https://tritonrankers.com/rankers/au/podcasts/2023/11), Hamish & Andy is the number 1 podcast in Australia with 2,091,717 monthly downloads. In the Podcast Index database it has a popularityScore of 7.

On the other hand, according to [OP3](https://op3.dev/show/c3e89eb0-73d9-597d-9188-9ba5285c28c4), Mere Mortals has a respectable 8,314 monthly downloads. In the Podcast Index database, it has a popularityScore of 9.

Assuming the popularity score uses some sort of a logarithmic scale, you might expect Mere Mortals to have a popularityScore of 4 (its monthly downloads figure contains 4 digits, while Hamish & Andy's contains 7 digits).

I would assume this is just the case of merging different sources of data with different scales into the same database without calibration. However I would be interested to know, what is the source of data for Mere Mortals, and what is the source of data for Hamish & Andy?

For example, perhaps all scores for Blubrry podcasts come from one source and all scores for Buzzsprout come from another source?

**Comment by daveajones** [comment]
We have no access to first party download data for any podcasts since we are only a podcast data provider and not the CDN. Our popularity scores are a measurement of how often the podcast apps that use us request data about individual podcasts from the API. That’s the best we can do with the information we have.

**Comment by ryan-lp** [comment]
Got it, thanks. For now the data is skewed in the direction of early adopters but it might become more reliable over time.
