### ISSUE TITLE
CSV: handling of line breaks

### ISSUE THREAD

**Issue by saerdnaer** [Podcastindex-org/database#5]
According to [RFC4180](https://tools.ietf.org/html/rfc4180#page-2) CSV should always use CRLF (aka `\r\n`) as line breaks:
```
 aaa,bbb,ccc CRLF
 zzz,yyy,xxx CRLF
```

Even for line breaks inside of fields (example 6, page 2):
```
"aaa","b CRLF
bb","ccc" CRLF
zzz,yyy,xxx
```

Right now https://archive.org/details/podcastindex_dump contains CRLF for line breaks at the end of a record, but only CR for line breaks inside of fields.

**Comment by datamythology** [comment]
I don't think the current csv output is suppose to be "used"
Just a quick & dirty output for us to look at some of the fields.
