### ISSUE TITLE
Is it possible / How to submit list of feeds?

### ISSUE THREAD

**Issue by keunes** [Podcastindex-org/database#8]
Hello,

I know the idea of PI is not to have individuals submit/propose individual podcasts. However, I would like to know if an exception could be made, or if there are other ways to get a particular set of podcasts listed.

The context: I'm helping out with AntennaPod and we've got quite a few folks chipping in complaining they can't find or subscribe to Radio France podcasts. Indeed - for some reason - their coverage in iTunes is bad. Now that we have implemented an option to search Podcast Index, I would like to get all these Radio France podcasts included, so that our users will get a proper experience.

If I manually scrape the list and provide a CSV that includes the RSS feeds/URLs, can this be imported somehow? Or would I need to request an API key with write/submit access? (which I don't want necessarily)

Many thanks anyway for your work!

**Comment by daveajones** [comment]
Absolutely.  Just email them to me:  dave@podcastindex.org .  I'll import them right in.  People submit feeds to us that way all the time.

**Comment by keunes** [comment]
Grand. Will do so this weekend. Thank you!
